 
legendas  sincronizao por: cyberrep  uin 7122353
para o arquivo: 648 mb 680423424 bytes

 
banco de sangue parizeka
praga republica checa

 
primeira vez que doa sangue

 
sim

 
eles pagam em dinheiro vivo
e no h limite de quanto pode doar

 
 compram at em potes

 
john newmack,  sua vez

 
nos ltimos 12 meses fez alguma tatuagem ou
foi submetido a exames de pele, sangue ou tecidos

 
no

 
e a cicatriz em seu queixo

 
um acidente na infncia

 
disse que no tem nenhum parente
correto

 
no que eu saiba

 
ningum a quem chamar em caso de uma emergncia
 no, ningum

 
sem familia
 j lhe disse que no

 
est me dizendo
que no posso ser doador

 
depende por que os resultados
de seus exames de sangue so muito incomuns

 
como incomum

 
seu sangue contm um fentipo muito estranho
que nunca haviamos visto antes

 
o que

 
do que est falando

 
quem so vocs

 
sentese por favor

 
que  isso

 
temos boas e ms noticias, john

 
boas noticias para ns

 
e ms para voc

 
vampiros

 
eu odeio vampiros

 
esquea o que voc sabe

 
vampiros existem

 
meu nome  blade

 
eu nasci metade humano

 
e metade vampiro

 
me chamam

 
de o que caminha de dia

 
tenho todos os seus poderes

 
e nenhuma de suas fraquezas

 
exceto pela sede

 
20 anos atrs conheci um homem
que mudou isso

 
whistler

 
ele me ensinou a controlar a sede

 
ele me ensinou as regras

 
me deu as armas para caar

 
prata

 
escurido

 
luz do sol

 
dois anos atrs foi atacado

 
levaramno e o converteram
naquilo que mais odeio

 
eu devia tlo matado

 
agora eu o estou caando

 
eu o encontrei

 
e nada

 
vai atravessar em meu caminho

 
eles subiram aqui, detenhaos

 
onde est

 
puta que pariu

 
no sei onde eles o prenderam

 
leveme at eles e o considerarei
um caso no solucionado

 
por favor
eu no sei

 
ele atirou em si mesmo
ns s o mantivemos vivo

 
sou eu rush, deixeme entrar

 
no atirem, sou eu

 
merda no  prata mas di
mais que a merda

 
termino com voc mais tarde

 
velho

 
veja o que te fizeram

 
vamos pra casa

 
tranquem suas filhas, meninos e meninas
por que o cavaleiro negro est de volta

 
quer provar um pouco 

 
no, mais tarde
apague as luzes

 
voc o encontrou

 
no o matou

 
me d uma mo

 
tenho um mal presentimento sobre isso b

 
escute como ele respira
j est morrendo

 
por que no terminamos
com sua dor agora mesmo

 
eles o mantinham em homoextse,
em uma casulo de transferncia

 
estou dando a ele um acelerador
de desintoxicao de retrovrus

 
com uma adio de herona

 
o que far com que no tenha
necessidade por uma noite

 
no vai funcionar por que no
mata esse filho da puta agora

 
saia daqui

 
se ainda h alguma parte de voc
whistler, escuteme

 
pela essas cortinas vo se abrir

 
esteja voc so

 
ou no

 
no foi minha inteno

 
escuteme blade

 
vai ter que me matar
no

 
deme a maldita arma

 
agora saia daqui

 
estpido filho da puta

 
como se sente

 
como merda amassada

 
como me encontrou

 
comecei em moscou depois romenia

 
mantiveram voc em movimento

 
por quanto tempo

 
meses

 
muito tempo

 
anos

 
me torturavam at me deixar
quase morto

 
me deixavam sarar em uma poa de sangue
para fazer tudo de novo

 
os filhos da puta podiam ter me
arrancado a perna

 
onde est mark

 
whistler  um prazer conhecelo
j ouvi muito sobre voc

 
pode me chamar de skud
todos me chamam assim

 
digame algo skidd

 
me chame de skud, como em stud

 
que seja

 
que est fazendo aqui

 
s umas modificaes fora do mercado
xido de nitrognio, coisas assim

 
aumentando o torque agregando
mais gases a combusto

 
todo o pacote pode dar
300 cavalos de fora

 
e queimlos todos antes da prxima
maldita mudana de cambio

 
e de onde tirou esse idiota

 
qual  o seu maldito problema velho

 
meu problema  que estive chupando
cogulos de sangue por dois anos

 
e fui salvo para ver que um qualquer est
fodendo com o trabalho de toda minha vida

 
colocamos nossas operaes em perigo s
para salvar te salvar, velho filho da puta

 
nossas operaes
 sim

 
nossas operaes
eu constru esta operao imbecil

 
sensores de movimento na zona 3, cavaleiros

 
humano 

 
temperatura corporal 50 f, creio que no

 
bem, esto usando bastes de magnsio

 
violaram seu sistema de segurana

 
pera

 
perapera

 
pera, pera, pera

 
bela roupa

 
luz do sol

 
ativarei o resto das bombas manualmente

 
nyssa guarde sua espada

 
foram os seus que deram o
primeiro tiro

 
estamos aqui para entregar uma mensagem

 
representamos o governo
da nao dos vampiros

 
esto lhe oferecendo uma trgua

 
eles querem marcar um encontro contigo

 
skud

 
tirem suas mscaras

 
meu nome  asad

 
e essa  nyssa

 
voc tem sido nosso pior inimigo

 
mas h algo mais solto nas ruas

 
algo pior que voc

 
que  to engraado

 
quantas histrias sobre blade e
o bugguy

 
na verdade estou decepcionada

 
ouviu isso b

 
est decepcionada

 
ele concordou em vir to fcilmente

 
vamos b, mostre a ela

 
por favor

 
sintax

 
h explosivo suficiente para
fazer desaparecer um quarteiro

 
decepcionada

 
os guardas parecen ser humanos b
podem ser conhecidos

 
est certo disso

 
bom, se no estou

 
o verdadeiro poder da
nao dos vampiros est aqui

 
pai

 
blade

 
esse  o overlord eli demoskilos

 
bem vindo caminhante do dia

 
estamos orgulhosos de nosso inimigo
e desfrutamos de seu exito

 
assim devo agradecerte

 
porque

 
eliminando a frost, nos fez um favor

 
kal kunen

 
voc  humano
apenas sou advogado

 
consrcio europeu de sade

 
como voc deve saber
o vampirismo  um arvovirus

 
levado na saliva dos predadores

 
em 72hrs dispersase pelo corpo
criando novos organismos parasitas

 
como o cncer

 
o cncer

 
com um propsito

 
desafortunadamente os vrus
tambm evoluem

 
ns encontramos um novo tipo
o tipo ripper

 
e como qualquer bom patonenio j
encontrou um portador

 
jarret nomack

 
nascido vampiro
mas uma anomalia como voc

 
mas, no como o resto de ns

 
 que s nos alimentamos de humanos,
ele se alimenta de vampiros tambm

 
creio que ele est me fazendo um favor
no est entendendo

 
suas vitimas vampiros no morrem,
se transformam

 
passam a ser portadores
voc tem que entender

 
essas coisas so como viciados em crack
necessitam de alimentao diariamente

 
nomack j est desperto a 72 horas

 
por nossas estimativas
j existem uma dezena de rippers

 
haver centenas em uma semana
milhares em alguns meses

 
faa as contas

 
deixemme entender

 
querem que eu os cace

 
 para vocs

 
quando terminarem com todos ns

 
quem pensa que sero os prximos

 
 seus queridos humanos

 
no sobrar nenhum deles

 
durante 2 anos treinamos uma pequena unidade
ttica: blood pack

 
queremos que voc os lidere

 
dois anos

 
estavamos treinandoos para te caar

 
ento b, o que acha

 
me soa como um plano

 
que pensa realmente

 
vo nos foder na primeira oportunidade

 
ento no vamos fazer isso, certo

 
ns vamos continuar

 
vai nos permitir saber mais sobre eles

 
vamos ter a oportunidade de ver
realmente como funciona seu mundo

 
j vi o suficiente de seu mundo

 
esto assustados porque j no
so os ltimos da cadeia

 
sabe, eu estou realmente preocupado por eles

 
eu sei que  seu amigo e tudo o mais,mas

 
creio que deveria ficar de olho

 
ningum perde a sede em uma noite

 
quer provar alguma coisa
pode ser

 
o que tem
nenhum problema

 
cavalo, hawaii nice

 
qualquer coisa que precisar
qualquer coisa que preciso

 
gosto disso

 
que acha se preciso de voc

 
doce sangue

 
estamos te esperando

 
caminhante do dia

 
blade

 
blood pack

 
vlad gema

 
verlaine

 
priest

 
snowman

 
chupa

 
e rhineheart

 
eu e o grupo estvamos curiosos

 
como  que 

 
se voc aguentaria

 
 isso a

 
ah, o que posso dizer

 
agora compreendo

 
vocs vem treinando a 2 anos para me matar

 
e agora, aqui estou

 
to excitante no 

 
ok

 
aqui est sua oportunidade

 
vamos

 
o que est esperando

 
aqui estou bem na sua frente

 
vamos

 
 sua primeira oportunidade

 
vamos, por que olha para ela

 
precisa de permisso

 
pode ser que precise de um incentivo, hein

 
ok eu posso te ajudar

 
que foi
no viu isso

 
est bem eu posso fazer outra vez

 
faa
reinhardt

 
faa
vamos

 
do que precisa de um manual

 
vamos reinhardt, mate o bastardo
vamos, faa

 
mateo agora

 
agora voc tem um explosivo preso
atrs de sua cabea

 
nitrato de prata

 
explodir se qualquer um tentar retirala

 
tenho o detonador aqui comigo

 
e se voc

 
se atrever a me olhar mal

 
a partir de agora somos uma equipe

 
e vocs obedecero minhas ordens

 
alguma pergunta

 
timo

 
se desejam caar o caador

 
comecem pela presa

 
iremos a todos os lugares noturnos
ondeos vampiros se encontram

 
bancos de sangue, caixas forte
quanto maior, melhor

 
ento

 
qual ser o primeiro

 
a casa da dor

 
onde  a entrada

 
no vejo nenhum anuncio

 
nenhum hieroglifo de vampiros

 
por sua causa tivemos que mudar
nossos hbitos

 
melhorams nossa segurana

 
veja de mais perto

 
legal

 
calibre 38, 45 e 9mm

 
todas com photocapsulas e as pontas revestidas
com nitrato de prata e extrato

 
harmas de hiper velocidade que disparam
uma estaca de prata a 600 ps por segundo

 
j que vocs sugadores no gostam da luz do sol

 
modifiquei a luz da ponta da arma
com um filtro de uv

 
abramna, e tero luz instantnea de uv

 
se estiver com o filtro, no haver problemas

 
hei b, veja isso

 
tem um mecanismo de liberao pneumtica

 
os contedores esto cheios de
um anticoagulante chamado edta

 
um golpe com isso
far explodir seu alvo

 
o cartucho  ejetado,
recarga automtica

 
legal

 
vamos

 
voc no passar como um de ns

 
de maneira alguma

 
como se eu me importasse
no, ele tem razo

 
por que no vigia l de cima do telhado

 
e cobre nossa retaguarda

 
ento o blood pack  quem
manda agora, no 

 
timo

 
melhor que controle esse seu velho
ou ns o faremos

 
continue pressionando imbecil

 
est a ponto de entrar no nosso mundo

 
voc ver coisas

 
sentir

 
apenas se lembre do porque de
estar aqui

 
no me esquecerei

 
o que exatamente esto procurando aqui

 
qualquer coisa que parea suspeita

 
s podem estar brincando comigo

 
skud est me ouvindo

 
skud

 
est me ouvindo

 
sim, estou ouvindo alto e claro b

 
todo o lugar  uma caixa forte

 
as janelas pintadas de preto so portas de sada

 
200 a 300 sanguesugas por aqui
isso parece bom

 
velho est me ouvindo

 
digame como est o tempo a em cima

 
como um dia de sol,
garoto

 
vejaos, nem a metade destes bastardos
so de sangue puro

 
eu te pergunto porque no matamos a todos

 
no faria diferena

 
deus, seria to fcil

 
te pegou

 
filho da puta

 
caminhante do dia

 


 
vocs tem meia hora antes que nasa o sol

 
precisamente

 
vi um deles mas o perdi

 
mantenham os olhos abertos

 
whistler
tem um em cima do onibus

 
nomack

 
caminhante do dia

 
que eu sou para voc

 
no  o inimigo do meu inimigo meu amigo

 
ou meu inimigo

 
esto atacando h 3 ou mais

 
luz do dia

 
que merda

 
a prata no lhes faz nada, no gastem balas

 
filho da puta

 
est me ouvindo, chupa

 
sorria

 
que besta mais feia

 
est sangrando foi mordido

 
minhas costas s feriu minhas costas

 
escutemme, usem as luzes de uv
no suportam a luz

 
priest
no iremos morrer aqui

 
vamos

 
priest caiu

 
o sol saiu

 
est szinho blade

 
se me quer tanto blade

 
aqui estou

 
por que me matar

 
voc e eu

 
temos o mesmo inimigo

 
queremos a mesma coisa

 
ns queremos a mesma coisa, blade

 
o que aconteceu

 
porque no me disse que eram
imunes a prata e ao alho

 
eu no sabia

 
se soubesse me contaria

 
acha que estou mentindo
para voc

 
ento por que no mato voc

 
quanto tempo faz que foi mordido

 
20 minutos

 
sua pele est queimando

 
est se transformando

 
algum por favor cala a boca
desse filho da puta

 
mateme logo, chupa

 
um homem sem medo

 
vamos, terminem com ele

 
no entendem, no podem
matalo dessa maneira

 
seguremno, seguremno

 
saiam

 
para trs

 
para trs

 
se esse  o grande blood pack,
estamos com graves problemas

 
esse filho da puta deixou seu posto

 
desapareceu

 
onde estava

 
encontrei um pouco de ao
com os rippers, tambm

 
ah  que  um pouco

 
perdemos um homem, priest

 
quer que escreva seu nome
em seu peito

 
deixeme mostrar a vocs

 
eu o vi movendose na ventilao,
seguio e o encontrei assim

 
creio que passaro por aqui

 
tentou entrar em seu esconderijo
e ficou preso pelo brao

 
acabou pior do que um coyote

 
mate esse desgraado

 
j est morrendo

 
preciso examinalo o mais rpido possivel

 
temos que desprendelo
vamos abrila

 
eles fizeram contatos com os rippers

 
alguma vitima

 
s uma

 
acredito que no tenha sido nissa

 
no

 
esse  um jogo muito perigoso
sr temiskinos

 
blade no  bobo

 
no vai poder continuar manipulandoo

 
voc se preocupa demais

 
todos os eventos esto se
realizando de acordo com o plano

 
j perdeu um

 
quantos est disposto
a sacrificar

 
a todos

 
incluidno a sua prpria filha

 
sim at ela

 
reconhece isso
 o banco de sangue

 
era um dos guardas

 
porque est morrendo
o que o est matando

 
o tempo

 
seu organimso est morrendo

 
no pode ficar sem sangue fresco por
muitas horas

 
se no comeam a alimentarse
de si mesmos

 
nomack  diferente

 
ele  o portador

 
tudo comeou com ele

 
 e terminar com ele

 
abra sua boca skud

 
abra a boca

 
b por favor

 
bichona

 
est bem

 
deus

 
s a lingua carrega o virus

 
 injetada por esses tentculos

 
tem massa muscular bifurcada
toda desenvolvida

 
a qual produz uma mordida
mito mais efetiva

 
a estrutura da mandibula
se mantm igual

 
mas no tem osso mandibular

 
pressione esse dente skud

 
neuro toxina

 
talvez paralizem a sua vitima
enquanto se alimentam

 
o alho no funciona,
a prata tampouco funciona

 
teremos que usar a luz do sol certo
 mortal para ns tambm

 
veremos o que mais podemos encontrar

 
suas feridas esto muito melhor

 
est sarando rpido

 
essas coisas so to diferentes
de ns

 
como ns somos de vocs

 
veja isso

 
o corao est envolto em osso
somento pelo lado  vulnervel

 
tem que se ter muita sorte
para matalos com uma estaca

 
retire a perna de uma aranha
e esta se mover sozinha

 
tentar caminhar sem estar
conectada ao corpo

 
que merda est fazendo

 
provando, certo

 
que merda  essa

 
o crebro est morto

 
 mas o corpo segue tentando alimentarse

 
faltam 6 horas para que o sol nasa

 
estejam preparados at l

 
e quando o sol nascer

 
blade, estou falando com voc

 
que acontecer quando amanhecer

 
ns vamos caar

 
sob a luz do sol

 
voc s pode estar brincando

 
tero que usar protetor solar,
branquelos

 
escuteme idiota

 
se continuar incomodando
te mando para o paraso

 
adoro quando voc fala assim

 
a luz solar  a nico meio que temos

 
estaro mais vulnerveis
ns tambm

 
temos que ser realistas

 
no espero que todos
reressem amanh

 
lembremse tenham cuidado

 
sempre

 
o que est procurando

 
bastes de fsforos
para extria a fonte de luz

 
e talvez possa fazer uma
granada de luz uv ou algo parecido

 
j hviamos tentado

 
mas no tinham o skud para
trabalhar nela, certo

 
blade

 
a forma com que fala com eles

 
que foi

 
estamos juntos nisso, lembrase

 
porque nos odeia tanto

 
 o destino

 
est em meu sangue
bom, tambm est no meu

 
eu sou de sangue puro,
nasci como vampiro

 
voc conhece a sede melhor
que qualquer um de ns

 
injetando esse esse seu soro

 
a nica diferena entre ns  que

 
eu assumi o que sou faz muito tempo

 
a quanto tempo que conhece o blade

 
j a quase 20 anos

 
no fala muito do passado

 
blade nunca fala muito de nada

 
quer ouvir uma coisa engraada

 
blade v voc como um pai

 
digame uma coisa

 
como se conheceram

 
eu estava mochilando

 
e conheci duas garotas

 
e decidi levalas pra minha barraca
para fazer uma orgia

 
lindo

 
me lembro apenas de janet e chrisy
arrancando pedaos do meu estomago

 
blade apareceu

 
e salvou meu rabo

 
o resto j no importa

 
vamos testar

 
de acordo

 
no funcionou, creio que tinha razo

 
voc tem um novo brinquedo

 
deixeme fazer uma pergunta

 
como vamos encontrar a esses
rippers

 
no ser necessrio

 
eles viro at ns

 
que merda  essa
feromonios

 
extrado das glandulas de
adrenalina do ripper

 
eles sero atrados por isso

 
querem que nos encharquemos
desta merda

 
usem suas armas de fogo
para encurralalos

 
depois lancem as granadas de uv

 
isto  para o granfinale

 
conecte algumas destas meninas
a um detonador

 
cuidado ao ativalo, ok

 
e voc no vir

 
no, sou um amante,
no um guerreiro

 
demoram 10 seg para explodir

 
nyssa

 
s lembrese de se proteger

 
 blade me d uma mo

 
voc e a senhorita muffet,
esto se tornado amigos

 
eu no me preocuparia

 
creio que est enganado
recordese de que lado est

 
no tem valor as palavras de um homem
que esteve 2 anos vivendo com o inimigo

 
que quer dizer

 
sabe whistler, h um velho ditado

 
mantenha seus amigos por perto
e seus inimigos mais perto ainda

 
espero que se lembre disso

 
blade

 
separemse em 3 unidades

 
queremos atrailos, no afugentalos

 
no podemos ver na escurido
que merda quer que eu faa

 
mantenha os olhos aberto
e evite ficar pra trs

 
veja isso

 
hey tio billy

 
que merda est fazendo

 
no h ningum aqui alm
de voc

 
 e ns

 
velhote

 
e blade perde um

 
perdemos um companheiro

 
no o deixe sair vivo

 
grupo de aranhas no tunel leste

 
preparando o pacote de bombas

 
nyssa

 
saiam

 
agora

 
no bastardos

 
vou atrailos at mim

 
faa o que lhe disser

 
movase

 
dez

 
nove

 
oito

 
sete

 
seis

 
cinco

 
quatro

 
trs

 
dois

 
um

 
reinhardt, reagrupar, agora

 
monte de sucata

 
chupa

 
saiam agora

 
que merda  essa

 
pretende me matar com mal
cheiro velho

 
chupa

 
saiam agora

 
chupa, saia da agora

 
espere

 
est bem
sim

 
temos que sair

 
temos muita companhia

 
todas as unidades, reagrupar

 
reagrupar

 
fodamse, filhos da puta

 
eles no caem

 
onde est o pacote de bombas

 
tive que deixalo nesse tunel

 
vo por esse tunel, movamse

 
no sabem com quem esto se metendo

 
a propsito blade

 
eu disse que a chave
do detonador est travada

 
chupem isso

 
vamos

 
querem uma mordida
ento vamos

 
vamos filhos da puta

 
whistler

 
espere

 
eu o deixarei viver

 
s pra dizer a blade

 
sobre esse anel

 
sobre a verdade

 
a verdade, velho

 
nyssa

 
voc fez um bom trabalho

 
no to bom, diria eu

 
que foi minha filha

 
eu lhe trouxe vergonha, pai

 
eu desonrei o braso da familia

 
blade me salvou

 
 valente e honrado

 
entendo

 
ainda est com vida

 
levaram todas as armas, at sua espada

 
algum estava informandoos

 
onde estamos

 
em algum tipo de calabouo

 
dentro do seu ninho

 
destruiram tudo

 
o trailer, tudo

 
mentiram para ns
desde o primeiro dia

 
o ripper no evolucionou

 
foi projetado

 
o que
projetado

 
nomack me disse

 
eu o vi nos esgotos

 
me deixou viver
  verdade

 
que generoso de sua parte

 
eu os trouxe aqui para que pudessem
ver os frutos de nosso trabalho

 
por anos temos lutamos

 
para eliminar qualquer debilidade
gentica de nossa espcie

 
modificar o dna era o passo seguinte

 
nomack foi o primeiro um erro

 
mas com um tempo

 
teremos uma nova raa pura

 
que obteremos de minha prpria carne

 
imune a prata

 
pronto para a luz do sol

 
eu tenho uma pergunta,
mentiroso filho da puta

 
como nomack obteve esse anel

 
eu acreditava que agora j
estaria obvio

 
eu dei a ele,  claro, um presente

 
de pai para filho

 
creio que j deixamos

 
o lobo junto com as ovelhas
tempo suficiente

 
reinhardt

 
beije seu traseiro, adeus

 
desculpe,  b

 
est perdendo tempo
a bomba  inutil

 
nunca iria explodir

 
s teria que lhe fazer sentir no controle

 
acreditava que tinhame sob
seu controle

 
muito melhor

 
pode ver isso

 
sou fiel a desmoskynos

 
precisavam de mim para trazelo
aqui e poder controlar o nomack

 
o velho de merda era
s armao

 
vejao
ele  a sua nica fraquesa

 
pode ser rpido, forte
e toda essa merda

 
mas no final b

 
 voc  muito humano

 
voc  um merda

 
pensaram que violaram
meu sistema de segurana

 
eu os deixei entrar, idiota

 
praticamente lhes dei as chaves

 
voc escutou o tubart
em breve todos sero caminhantes do dia

 
quando isso ocorrer

 
eu prefiro seu um mascote do que
gado, entente b

 
que acha disso

 
2 coisas

 
uma

 
eu sabia, desde que te atacaran

 
e dois

 
no era uma bomba inutil

 
fantstico

 
j comeava a gostar

 
matemnos

 
vamos examinar todo seu sangue

 
cada gota dele

 
depois a medula espinhal, orgos, tudo

 
encontraremos a chave que nos falta
para criar caminhantes do dia

 
isso pode doer um pouco

 
legal

 
quantos vampiros j matou com essa coisa

 
no o suficiente, fritz

 
continue falando

 
 s far com que eu desfrute
mais ao lhe enviar para o inferno

 
estou bem aqui

 
faa tua pior merda, galinha

 
ajustaremos as contas depois

 
que mais devo fazer

 
eu confiei em voc

 
com meus homens

 
minha vontade

 
minha vida

 
voc no me mandou apenas l fora

 
voc me mandou para a morte

 
o inimigo me salvou a vida 2 vezes
e voc nos usou

 
a seus propios filhos

 
voc no se equivocou nyssa

 
os laos sanguineos

 
 no significam nada ao lado
da excelencia de nossa raa

 
a quem acredita que favorece deus
na rede

 
a aranha ou a mosca

 
nomack

 
que tem ele, hum

 
ele quer vingana

 
todos as pessoa que

 
 o criou

 
voc pode ter razo

 
mas afortunadamente para ns

 
ele no sabe desse lugar

 
no

 
sim, ele conhece

 
que merda

 
vamos, nem pense em morrer

 
no se d por vencido comigo

 
eu tampouco o faria por voc

 
vamos, blade

 
sangue

 
sim

 
sangue

 
pai

 
ele nunca entrar aqui

 
pai

 
pai

 
voc consegue

 
v

 
bom

 
como disse meu pai antes de
matar a minha me

 
se quer que algo seja bem feito,
tem que fazer voc mesmo

 
ele tambm dizia

 
quer uma mo

 
oi garoto

 
troquei o cdigo de segurana

 
estamos trancados

 
est maluca

 
ele matar ns dois

 
sim

 
 trite que no morrer
nas mos de seu inimigo

 
e sim nas de seus prprios filhos

 
pai

 
tudo o que aconteceu

 
foi uma terrivel tragdia

 
um erro sem perdo

 
mas volte comigo

 
encontraremos uma cura

 
tome seu lugar ao meu lado

 
depois de tudo, voc  um prncipe
juntos conquistaremos tudo

 
se o que diz  verdade

 
por que sua voz treme

 
pai

 
ser perdoado pai,
voc morrer

 
fora desta feria seus sangue
 sua vida  fluir

 
nyssa

 
acabe meu irmo

 
fechemos o circulo

 
voc

 
voc era sua favorita

 
soltea

 
blade

 
terminamos aqu

 
o que voc acha

 
ainda no acabou

 
depois de tudo

 
parece que vou terminar
fazendo o trabalho do meu pai

 
que estranho

 
dor

 
j no doi mais

 
j posso sentir queimando por dentro

 
quero morrer ainda sendo um vampiro

 
quero ver o sol

 
no tardar muito

 
pode usar o nmero 3, aprecieo

 
est certo que as garotas esto vivas

 
estavam vivas na ltima vez que as vi

 
obrigado

 
um par de lminas de barbear caso precise

 
no pensou que havia esquecido de voc,
pensou

 
sincronizao por: surfmaniacbr
traduo: surfmaniacbr

